### ISSUE TITLE
Allow auto-filtering

### ISSUE THREAD

**Issue by daj92109** [Nayjest/ViewComponents#27]
Hello,
I love your components.  I've learned a lot by reading the code.  One enhancement I'd like to see is the ability to filter the displayed items simply by selecting the drop-downs.  Clicking the "Filter" button is an unnecessary step.

**Comment by Nayjest** [comment]
Hi!
Thanks for suggestion. Autosubmitting was present in nayjest/grids package but not moved yet to view-components. 

Give me few minutes, I will implement this now.

**Comment by Nayjest** [comment]
Released in [0.24.4](https://github.com/view-components/view-components/releases/tag/v0.24.4)
See https://github.com/view-components/view-components/commit/f2dc7f375289c35292b82f1513b87c5a0529a1e4
https://github.com/view-components/view-components/commit/74ed5199bd61fa19688c8f65ed058d4130e2663b

Code example:

``` php
$list = new ManagedList(
    $dataProvider,
    [
        new RecordView(new SymfonyVarDump()),
        (new SelectFilterControl(
            'role',
            [
                '' => 'All Roles',
                'User' => 'Users',
                'Manager' => 'Managers',
                'Admin' => 'Admins',
            ],
            new InputOption('role', $_GET)
        ))->enableAutoSubmitting(),
        (new PageSizeSelectControl(new InputOption('page_size', $_GET), [5,10]))->enableAutoSubmitting(),
        new PaginationControl(new InputOption('p', $_GET, 1), 5)
    ]
);
echo $list->render();
```

**Comment by Nayjest** [comment]
Note that submit button will hide automatically if all autosubmitting enabled for all controls that requires  submit button (see isManualFormSubmitRequired() method)

**Comment by daj92109** [comment]
Very nicely done.  Thanks for the quick response too!

I've sound that my existing FilterControl does not have the new 
enableAutoSubmitting() method.  (My sample code is show below.) Do you 
recommend that I change it to a SelectFilterControl?

(new FilterControl('type', FilterOperation::OPERATOR_STR_CONTAINS, 
$input('type')))->setView(
     new TemplateView('select', [
         options' => [
             '' => 'All Roles',
             'User' => 'Users',
             'Manager' => 'Managers',
             'Admin' => 'Admins',
         ]
     ])
),//->enableAutoSubmitting(),

**Comment by Nayjest** [comment]
There is possibility to enable it in view of select input:

``` php
new FilterControl('type', FilterOperation::OPERATOR_STR_CONTAINS,
$input('type')))->setView(
     new TemplateView('select', [
         'autoSubmit' => true, //     <--- here is solution
         'options' => [
             '' => 'All Roles',
             'User' => 'Users',
             'Manager' => 'Managers',
             'Admin' => 'Admins',
         ]
     ])
),
```

But in this case FilterControl::isManualFormSubmitRequired() will return true and main component(List/Grid) will add submit button to controls (you can remove it manually).
