### ISSUE TITLE
how to add html class to filter control field 

### ISSUE THREAD

**Issue by sunel** [Nayjest/ViewComponents#30]
``` php
(new FilterControl('start_date', FilterOperation::OPERATOR_GTE, $input->option('start_date')))->setView(
     new TemplateView('input', [
            'class' => 'datepicker',
     ])
),
```

But it dosen't  get add to the element

**Comment by Nayjest** [comment]
Hi!
See https://github.com/view-components/view-components/blob/master/resources/views/input.php

You need

``` php
new TemplateView('input', [
    'inputClass' => 'datepicker',
])
```

or

``` php
new TemplateView('input', [
    'containerClass' => 'datepicker',
])
```

**Comment by Nayjest** [comment]
You can do it also following way:

``` php
...
$startDateFilter =  new FilterControl(
    'start_date',
    FilterOperation::OPERATOR_GTE,
    $input->option('start_date')))
),
...
// somewhere below but before grid rendering
$startDateFilter->getView()->setDataItem('inputClass', 'datepicker');

```

**Comment by Nayjest** [comment]
Another tip:
Try:

``` php
new TemplateView('input', [
    'inputType' => 'date',
])
```

If you use bootstrap styling it will autobatically add bootstrap-datepicker for date inputs.

**Comment by sunel** [comment]
I Tried both but its didn't work

``` php
new TemplateView('input', [
    'inputClass' => 'datepicker',
])
```
or
```php
new TemplateView('input', [
    'containerClass' => 'datepicker',
])
```

**Comment by sunel** [comment]
That worked

Can you have the doc for this package

**Comment by Nayjest** [comment]
If you want, you can help with docs, just click "edit" on pages below :)

Available documentation: 
- [Cookbook](https://github.com/view-components/view-components/blob/master/doc/cookbook.md)
- [Component Overview](https://github.com/view-components/view-components/blob/master/doc/components.md)
- [Readme](https://github.com/view-components/view-components/blob/master/README.md)

**Comment by sunel** [comment]
Sure
