### ISSUE TITLE
ViewComponents\ViewComponents\Component\ManagedList\RecordView::__construct() must implement interface ViewComponents\ViewComponents\Base\DataViewComponentInterface

### ISSUE THREAD

**Issue by dvgorkovoy** [Nayjest/ViewComponents#32]
Hi! Your demo is nice but I tried to run your demo and I was stopped with this
http://storage6.static.itmages.com/i/16/0812/h_1471005897_8836660_c10d2f20bd.png 

I think something wrong with interfaces

**Comment by Nayjest** [comment]
Hi!

Thanks for submitting issue.

Which demo fails? I checked all demos, don't see such error. There are also tests for all demos and it works for me (`composer test` command runs local web-server & checks http status (200) for each demo).

Please provide more details and I will fix it during few next hours.

While issue isn't fixed, you can temporary downgrade view-components to v0.25.1, there is no such DataViewComponentInterface interface requirement.

**Comment by dvgorkovoy** [comment]
Sorry, I had to create issue here  https://github.com/view-components/grids/issues
I installed Stand-alone Project  **composer create-project view-components/grids**
And then tried to run Your demo controller ( that https://github.com/view-components/grids/blob/master/tests/webapp/Controller.php )  
No matter what action run all of them falls here 
/var/www/grid/src/Grid.php in line 133 
please look at images:
http://storage2.static.itmages.com/i/16/0815/h_1471234302_9226199_4d79f7e493.png

class **Tag** does not have interface **DataViewComponentInterface** 
http://storage1.static.itmages.com/i/16/0815/h_1471234410_8890220_25a9a81b34.png

but that interface needed here: 
http://storage2.static.itmages.com/i/16/0815/h_1471234524_7966357_14a472f662.png

Thank you.

**Comment by dvgorkovoy** [comment]
Now I try to use base Example (on page https://github.com/view-components/grids ) and there is the same error

**Comment by Nayjest** [comment]
Please update your packages to get it working  (run `composer update`)

**Comment by dvgorkovoy** [comment]
Thank You very much!
