### ISSUE TITLE
Problem with column sorting and postgres with pagination

### ISSUE THREAD

**Issue by Digital-Daz** [Nayjest/ViewComponents#33]
When using column sorting with postgres and error is returned.

The error only happens when you have column sorting AND pagination.

Method ViewComponents\Grids\Grid::__toString() must not throw an exception, caught Illuminate\Database\QueryException: SQLSTATE[42803]: Grouping error: 7 ERROR: column "clientaccounts.last_name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...nt(*) as aggregate from "clientaccounts" order by "last_name...
^ (SQL: select count(*) as aggregate from "clientaccounts" order by "last_name" asc)

This does not seem valid postgres sql: select count(*) as aggregate from "clientaccounts" order by "last_name" asc

**Comment by Nayjest** [comment]
Hi!

I have no installed postgres now to make some tests. Can you check: will it fix this issue if we will remove  order by ... from query that calculates record count for pagination (its really useless there)?

**Comment by Digital-Daz** [comment]
Hi, yes, I think this works, it seems to come in in $operations and if I remove it from there then it works.

**Comment by Nayjest** [comment]
If my previous suggestion works (I'm wayting for your answer), we have few options:

Solution 1: 
Modify [PaginationControl::getTotalRecordsCount()](https://github.com/view-components/view-components/blob/master/src/Component/Control/PaginationControl.php#L97): remove all instances of [SortOperation](https://github.com/view-components/view-components/blob/master/src/Data/Operation/SortOperation.php) 
and then restore it after getting count.

Solution 2:
1. Remove all instances of SortOperation in DataProvider::count()  and then restore it after getting count
Here:

https://github.com/view-components/view-components/blob/master/src/Data/ProcessingService/DbTableProcessingService.php
https://github.com/view-components/eloquent-data-processing/blob/master/src/EloquentProcessingService.php
https://github.com/view-components/doctrine-data-processing/blob/master/src/DoctrineProcessingService.php

**Comment by Nayjest** [comment]
I can fix that after few hours, have urgent work now.
But if you want, you may contribute with any of described solutions, probably it will be faster than I can do it.

**Comment by Digital-Daz** [comment]
Nayjest, I would love to but unfortunately it is completely way above my current skillset.

**Comment by Nayjest** [comment]
Released in v0.26.6

Please upd. package to v0.26.6 & let me know if it helped.

**Comment by Digital-Daz** [comment]
Thank you, seems to work perfectly.
